version: "3"

services:
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - botnet
  bot:
    build: .
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - botnet
networks:
  botnet:
    driver: bridge
volumes:
  db-data:
