"""empty message

Revision ID: 7acb33fab6a0
Revises: 
Create Date: 2023-05-01 12:00:19.709070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acb33fab6a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finishedquizzess', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'finishedquizzess', ['poll_id'])
    op.drop_constraint('finishedquizzess_question_id_fkey', 'finishedquizzess', type_='foreignkey')
    op.create_foreign_key(None, 'finishedquizzess', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finishedquizzess', type_='foreignkey')
    op.create_foreign_key('finishedquizzess_question_id_fkey', 'finishedquizzess', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'finishedquizzess', type_='unique')
    op.alter_column('finishedquizzess', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
